package com.maybeitssquid.sensitive;

import java.util.Arrays;

/**
 * A {@link Sensitive} value that backed by multiple segments of the same type.
 *
 * @param <T> the type of the individual segments. This type should have well-defined {@link Object#equals(Object)} and
 *            {@link Object#hashCode()} methods so that the corresponding methods on this class meets the contract.
 */
@SuppressWarnings("unused")
public class Segmented<T> extends Sensitive<T[]> {

    public Segmented(final Renderer<T[]> renderer, final T[] contained) {
        super(renderer, contained == null ? null : contained.clone());
    }

    /**
     * Returns a clone of the contained array to prevent external mutation.
     * This override provides additional protection for array-backed sensitive data.
     *
     * @return a clone of the contained array
     */
    @Override
    protected final T[] getContained() {
        return super.getContained().clone();
    }

    /**
     * Returns the hash of the enclosed {@code raw} data as generated by invoking {@link Arrays#hashCode(Object[])}
     * on the contained raw data.
     *
     * @return {@inheritDoc}
     */
    @Override
    public int hashCode() {
        return Arrays.hashCode(super.getContained());
    }

    /**
     * Returns true if the types match and the enclosed raw data are equal as indicated by invoking
     * {@link Arrays#equals(Object[], Object[])}.
     *
     * @param o {@inheritDoc}
     * @return {@inheritDoc}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Segmented<?> segmented = (Segmented<?>) o;

        return Arrays.equals(super.getContained(), segmented.getContained());
    }
}
